trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CONTAINER_REGISTRY: pipelinepocs.azurecr.io
  IMAGE_NAME: pipeline_acr/wso2am/wso2am
  TAG: latest

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'azuresconn'
    KeyVaultName: 'passwordacr'
    SecretsFilter: '*'
    RunAsPreJob: true

- script: |
    timestamp=$(date +%s)
    docker login docker.wso2.com --username=ketharan@wso2.com --password=$(dockerpass)
    docker pull  docker.wso2.com/wso2am:latest
    docker login pipelinepocs.azurecr.io --username=pipelinepocs --password=$(password)
    docker tag docker.wso2.com/wso2am:latest pipelinepocs.azurecr.io/wso2/wso2am:$timestamp
    docker push pipelinepocs.azurecr.io/wso2/wso2am:3.2.0
  displayName: 'Transfer the latest image to ACR'

