trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CONTAINER_REGISTRY: pipelinepocs.azurecr.io
  IMAGE_NAME: pipeline_acr/wso2am/wso2am
  TAG: latest

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'azuresconn'
    KeyVaultName: 'passwordacr'
    SecretsFilter: '*'
    RunAsPreJob: true

- script: |
    docker pull wso2/wso2am:3.2.0
    docker login pipelinepocs.azurecr.io --username=pipelinepocs --password=$(password)
    docker tag wso2/wso2am:3.2.0 pipelinepocs.azurecr.io/wso2/wso2am:3.2.0
    docker push pipelinepocs.azurecr.io/wso2/wso2am:3.2.0
  displayName: 'Transfer the latest image to ACR'

