trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CONTAINER_REGISTRY: pipelinepocs.azurecr.io
  IMAGE_NAME: pipeline_acr/wso2am/wso2am
  TAG: latest

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'subscribtionServiceConnection'
    KeyVaultName: 'acr-password'
    SecretsFilter: '*'
    RunAsPreJob: true

- script: |
    docker pull wso2am/wso2am:3.1.0-beta
    docker login pipelinepocs.azurecr.io --username=pipelinepocs --password=$(acrpass)
    docker tag wso2am/wso2am:3.1.0-beta pipelinepocs.azurecr.io/wso2am/wso2am:latest
    docker push pipelinepocs.azurecr.io/wso2am/wso2am:latest
  displayName: 'Run a one-line script'

#commit test