# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CONTAINER_REGISTRY: pipelinepocs.azurecr.io
  IMAGE_NAME: pipeline_acr/wso2am/wso2am
  TAG: latest

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure subscription 1(7eb13158-f96c-48b3-900f-9c9c83906ac7)'
    KeyVaultName: 'acrpass'
    SecretsFilter: '*'
    RunAsPreJob: true
- script: |
    docker pull wso2am/wso2am:3.1.0-beta
    docker login pipelinepocs.azurecr.io --username=pipelinepocs --password=SF+RkUmP0ACWlqW8f5OPVClRF4ceq7tC
    docker tag wso2am/wso2am:3.1.0-beta pipelinepocs.azurecr.io/wso2am/wso2am:latest
    docker push pipelinepocs.azurecr.io/wso2am/wso2am:latest
  displayName: 'Run a one-line script'
  #commits

